# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: cultureondemand
    build: .
    command: uwsgi --http 0.0.0.0:5000 --module cultureondemand.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/cultureondemand.db
    volumes:
      - ./cultureondemand:/code/cultureondemand
      - ./db/:/db/
    ports:
      - "5000:5000"
